.Dd July 03, 2021
.Dt httpserve 1
.Os
.Sh NAME
.Nm httpserve
.Nd simple webserver utility
.Sh SYNOPSIS
Creates an http server on localhost:8000 by default, serving whatever has been passed in through stdin.
.Sh DESCRIPTION
Serve stdin to a localhost port, you can add as many custom response headers you want with the -h option. The port number defaults to 8000. This application was born from the need to set aribitrary http headers quickly to see what effects they have on content being served.
.El
.SH MODIFIERS
.Bl -tag -width XX
.It -h <header>
Set custom http response headers. I.e -h 'Content-Type: text/html'
.It -p <port>
.i port
.Rs
The localhost port number, defaults to 8000.
.El
.Sh EXAMPLES
.Bl -tag -width XX
.It echo '<html></h1>Hello, world!</h1></html>' | httpserve
.Pp
reads the html from stdin and serves it on localhost:8000 
.Pp
.It echo '<html></h1>Hello, world!</h1></html>' | httpserve -p 9000 -h 'Content-Type: text/html' -h 'Connection: close'
.Pp
reads the html from stdin and serves it on localhost:9000, sets custom http response headers.
.Sh AUTHOR
.An James Barford-Evans.
.Sh DOCUMENTATION & SOURCE
.Pp
Full documentation and source code <https://github.com/Jamesbarford/httpserve>
